---
- hosts: all
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
      notify:
        - deploy index.html
  handlers:
    - name: deploy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
