---
- hosts: dev
  become: true
  tasks:
    - name: Download tomcat 10 binaries
      get_url:
         url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.7/bin/apache-tomcat-10.1.7.tar.gz
         dest: /opt
    - name: Extract the binaries
      unarchive:
        src: /opt/apache-tomcat-10.1.7.tar.gz
        dest: /opt
        remote_src: yes

    - name: Rename the apache-tomcat-10.1.7 directory
      command:
        chdir: /opt
        cmd: mv apache-tomcat-10.1.7 tomcat
